name: beuber
description: BeUber – Darslar, AI, Zoom, Sertifikat tekshiruv, Homework, Gamifikatsiya
publish_to: 'none' # private project

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Lokalizatsiya + tillarni avtomatik tanlash
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # State management (responsive UI uchun)
  provider: ^6.1.2

  # Routing
  go_router: ^12.1.1

  # HTTP so‘rovlar
  http: ^1.2.1

  # Realtime Chat + Video Call (WebRTC uchun)
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.50

  # Sertifikat yoki rasm yuklash
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  path_provider: ^2.1.2

  # Animatsiyalar va loadinglar
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # PDF ko‘rish, yuklash
  syncfusion_flutter_pdfviewer: ^24.2.8

  # Responsive dizayn
  flutter_screenutil: ^5.9.0

  # Tokenlar va JWT bilan ishlash
  flutter_secure_storage: ^9.0.0

  # Tizim tillarini aniqlash
  device_info_plus: ^10.0.0
  package_info_plus: ^5.0.1

  # Platformaga mos sozlash (Android/iOS)
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0

  # Matematik, AI funktsiyalar
  dart_eval: ^0.7.0

  # AI uchun JSON va tozalovchi modullar
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  intl_utils: ^2.8.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
    - assets/pdf/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
