name: beuber
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  file_picker: ^8.0.6
  mime: ^2.0.0
  zego_uikit_prebuilt_call: ^4.16.28
  zego_uikit: ^2.20.0
  image_picker: ^1.1.1
  emoji_picker_flutter: ^4.3.0
  socket_io_client: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
  generate: true
