name: beuber
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  file_picker: ^6.1.1
  mime: ^1.0.4
  zego_uikit_prebuilt_call: ^3.9.5
  zego_uikit: ^2.20.0
  image_picker: ^1.1.1
  emoji_picker_flutter: ^1.6.1
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
  generate: true
